// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DialogWarning(arg1) {
  return window['go']['main']['App']['DialogWarning'](arg1);
}

export function RunCapture(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCapture'](arg1, arg2, arg3);
}

export function SaveRows(arg1) {
  return window['go']['main']['App']['SaveRows'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}
