// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DialogWarning(arg1:string):Promise<void>;

export function RunCapture(arg1:string,arg2:number,arg3:boolean):Promise<main.AllResult>;

export function SaveRows(arg1:Array<main.Result>):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;
